import Link from "next/link";
import type { ReactNode } from "react";
import "./kablitz-projekt.css";

const chapters = ["Website & Inhalte", "Interaktive Präsentation", "CMS & Administration", "SEO & AEO", "Umsetzung & Übergabe", "Betreuung & nächste Phase"];
function Sheet({ number, title, children }: { number: number; title: string; children: ReactNode }) {
  return <section className="offer-sheet" id={`kapitel-${number}`} aria-labelledby={`titel-${number}`}>
    <header className="offer-sheet-head"><span>ADSPIRE / KABLITZ</span><span>Leistungsangebot · {String(number).padStart(2, "0")}</span></header>
    <div className="offer-section-title"><span>{String(number).padStart(2, "0")}</span><h2 id={`titel-${number}`}>{title}</h2></div>
    {children}
    <footer className="offer-sheet-foot"><span>Neue Unternehmenswebsite · Leistungsumfang</span><span>{String(number + 1).padStart(2, "0")} / 07</span></footer>
  </section>;
}
function Block({ title, children }: { title: string; children: ReactNode }) { return <div className="offer-block"><h3>{title}</h3>{children}</div>; }

export function KablitzProjektPage() {
  return <main className="offer">
    <nav className="offer-toolbar" aria-label="Dokumentnavigation"><Link href="/">← Zur Demo</Link><span>Leistungsangebot</span><a href="#inhalt">Inhalt ↓</a></nav>
    <div className="offer-document">
      <section className="offer-sheet offer-cover" aria-labelledby="angebot-titel">
        <header className="offer-sheet-head"><strong className="offer-brand">ADSPIRE</strong><span>Für Richard Kablitz GmbH</span></header>
        <div className="offer-cover-body"><p className="offer-cover-type">Leistungsangebot / Projektumfang</p><h1 id="angebot-titel">Die neue digitale<br />Präsenz von<br /><em>Kablitz.</em></h1><p className="offer-lead">Eine mehrsprachige Unternehmenswebsite mit interaktiver Industriepräsentation, zentraler Redaktion und strukturierten Kundenanfragen.</p><div className="offer-cover-rule" /><dl className="offer-facts"><div><dt>Umsetzung</dt><dd>Maximal 2 Monate</dd></div><div><dt>Sprachen</dt><dd>DE / EN + ES / FR / IT</dd></div><div><dt>Betreuung</dt><dd>3 Monate inklusive</dd></div></dl></div>
        <div className="offer-parties"><div><small>Auftraggeber</small><strong>Richard Kablitz GmbH</strong><span>Unternehmenswebsite & Administration</span></div><div><small>Auftragnehmer</small><strong>ADSPIRE · Đorđe Mladenović</strong><span>Dimitrija Leka 66, 18000 Niš (Palilula), Serbien</span><span>PIB 114723739 · MB 67804961</span></div></div>
        <footer className="offer-sheet-foot"><span>Arbeitsfassung · ohne Preisangaben · 01. Oktober 2026</span><span>01 / 07</span></footer>
      </section>
      <Sheet number={1} title="Website & Inhalte">
        <p className="offer-intro">Der bestehende Demo-Auftritt bildet die gestalterische Grundlage. Daraus entsteht eine vollständige, produktive Unternehmenswebsite für Vertrieb, technische Information und Service.</p>
        <aside className="offer-callout"><h3>Keine vorab festgelegte Begrenzung der Seitenzahl.</h3><p>Der Umfang richtet sich nach den fachlichen Anforderungen und der SEO-/AEO-Strategie. Alle im Projekt abgestimmten relevanten Seiten sind enthalten; die Erstellung wird nicht pro Seite berechnet. Neue Funktionen und laufende Erweiterungen nach Projektabschluss werden separat abgestimmt.</p></aside>
        <Block title="Vollständiger Unternehmensauftritt"><p>Startseite, Unternehmen, Geschichte, Fertigung und Gießerei, Kontakt, Karriere sowie erforderliche rechtliche Informationsseiten. Ergänzt durch alle relevanten Fachseiten zu Lösungen, Technologien, Anlagen, Brennstoffen, Anwendungen, Service und Ersatzteilen.</p></Block>
        <Block title="Abgeschlossene und aktuelle Projekte"><p>Jedes zur Veröffentlichung freigegebene Projekt erhält eine eigene Detailseite mit Status, Standort, Bildern, Beschreibung und relevanten technischen Daten. Die Kategorien „Abgeschlossene Projekte“ und „Aktuelle Projekte“ werden im CMS, in der Projektübersicht und auf dem Globus einheitlich verwendet. Die Einordnung zukünftiger Projekte wird mit Kablitz abgestimmt.</p></Block>
        <Block title="Fünf Sprachversionen"><p>Deutsch und Englisch sind die gewählten Hauptsprachen. Spanisch, Französisch und Italienisch werden für den anfänglichen Projektumfang ohne zusätzliche Berechnung ergänzt. Navigation, Formulare und veröffentlichte Inhalte werden entsprechend mehrsprachig umgesetzt.</p></Block>
        <Block title="Inhalte gemeinsam vorbereiten"><p>Kablitz liefert Fotos, wesentliche Fachinformationen und vorhandene Texte. ADSPIRE erstellt und überarbeitet daraus die Website-Texte und Sprachversionen. Fachliche Angaben, Übersetzungen, Bildrechte und die Veröffentlichung von Projekten werden durch Kablitz freigegeben.</p></Block>
        <nav id="inhalt" className="offer-contents" aria-label="Inhaltsverzeichnis"><h3>In diesem Angebot</h3><ol>{chapters.map((title, index) => <li key={title}><a href={`#kapitel-${index + 1}`}><span>{String(index + 1).padStart(2, "0")}</span>{title}<span>↗</span></a></li>)}</ol></nav>
      </Sheet>
      <Sheet number={2} title="Interaktive Präsentation">
        <p className="offer-intro">Die charakteristischen Elemente der Demo bleiben zentral: eine ausdrucksstarke Startseite, der interaktive 3D-Globus und die anschauliche Darstellung des Anlagenprozesses.</p>
        <Block title="Interaktiver 3D-Globus"><p>Ein drehbarer, interaktiver Globus macht die internationale Präsenz und Entwicklung von Kablitz erlebbar. Jede dargestellte Standort- oder Projektmarkierung ist anklickbar und öffnet zugehörige Informationen sowie den Zugang zur Detailseite.</p><ul><li>Historische Entwicklung des Unternehmens und Erweiterungen des Werks entlang einer Zeitachse.</li><li>Abgeschlossene und aktuelle Projekte; freigegebene zukünftige Vorhaben können ebenfalls dargestellt werden.</li><li>Filter zur gezielten Auswahl von Projekten und historischen Ereignissen.</li><li>Projektvorschau mit Bildern, Standort, Status und wesentlichen Daten.</li><li>Pflege von Projektinformationen, Koordinaten und zeitlicher Einordnung über das CMS.</li></ul><p>Mehrere Ereignisse am gleichen Standort werden zeitlich getrennt dargestellt. Eine ergänzende Projektliste ermöglicht den Zugriff auch ohne Bedienung der 3D-Ansicht.</p></Block>
        <aside className="offer-callout"><h3>Der Anlagenprozess: vollständig auf Kablitz zugeschnitten.</h3><p>Direkt nach dem Globus erklärt die bereits vorgestellte interaktive Sektion die Funktionsweise der Anlage. Die Darstellung wird anhand der technischen Vorgaben von Kablitz weiter ausgearbeitet.</p></aside>
        <Block title="Vom Brennstoff bis zur Energie"><p>Die animierte Prozessdarstellung zeigt Brennstoffzuführung, Feuerung, Energieerzeugung und Rauchgasbehandlung. Aufbau, Prozessschritte, Komponenten, Bezeichnungen, Texte und Animationen können vollständig an die tatsächliche Kablitz-Technologie angepasst und weiter verfeinert werden, bis der freigegebene Ablauf fachlich korrekt dargestellt ist.</p><p>Die Abstimmung erfolgt anhand der von Kablitz bereitgestellten technischen Informationen. Die Sektion ist eine erklärende Visualisierung und keine Live-Steuerung oder technische Simulation.</p></Block>
        <Block title="Qualität auf allen Geräten"><p>Responsive Umsetzung für Desktop, Tablet und Smartphone, verständliche Navigation und zugängliche Bedienung. Animationen berücksichtigen reduzierte Bewegung; Bilder und 3D-Inhalte werden für kurze Ladezeiten und eine flüssige Nutzung optimiert.</p></Block>
        <div className="offer-flow" aria-label="Prozessübersicht"><span>01<br /><strong>Brennstoff</strong></span><span>02<br /><strong>Feuerung</strong></span><span>03<br /><strong>Energie</strong></span><span>04<br /><strong>Rauchgas</strong></span></div>
      </Sheet>
      <Sheet number={3} title="CMS & Administration">
        <p className="offer-intro">Ein geschützter Arbeitsbereich verbindet die Pflege der Website mit der Bearbeitung von Projekt- und Serviceanfragen. Rollen und Arbeitsabläufe werden auf die Organisation von Kablitz zugeschnitten.</p>
        <Block title="Google-Anmeldung & Mitarbeiterverwaltung"><p>Sign in with Google für zuvor freigeschaltete E-Mail-Adressen. Owner und berechtigte Administratoren können Mitarbeiter hinzufügen, Rollen zuweisen und Zugänge deaktivieren. Berechtigungen werden serverseitig geprüft.</p><p>Der Owner erhält vollständigen Zugriff. Redaktion, Vertrieb und Service erhalten die jeweils benötigten Rechte. Sichtbarkeit, Veröffentlichung und Zuständigkeiten werden gemeinsam definiert.</p></Block>
        <div className="offer-table-wrap"><table className="offer-table"><caption>Module der ersten Phase</caption><thead><tr><th>Modul</th><th>Enthaltene Funktionen</th></tr></thead><tbody>
          <tr><th scope="row">CMS & Medien</th><td>Abgestimmte Seiteninhalte, Bilder und Sprachversionen bearbeiten. Definierte Felder und Sektionen erhalten die Qualität des Designs.</td></tr>
          <tr><th scope="row">News</th><td>Beiträge erstellen, bearbeiten, als Entwurf speichern und veröffentlichen; Anzeige auf der Startseite und den News-Seiten.</td></tr>
          <tr><th scope="row">Projekte</th><td>Abgeschlossene und aktuelle Projekte mit Bildern, Fachinformationen, Standort und Detailseite verwalten; Verknüpfung mit dem Globus.</td></tr>
          <tr><th scope="row">Projektanfragen</th><td>Technische Angaben und Kontaktdaten, Vorgangsnummer, Detailansicht, Filter, Status, interne Notizen und Zuweisung an Mitarbeiter.</td></tr>
          <tr><th scope="row">Serviceanfragen</th><td>Service- und Ersatzteilanfragen, mehrere Teilepositionen, Fotos und Zeichnungen; Status, interne Notizen und Zuständigkeit.</td></tr>
          <tr><th scope="row">Analytik</th><td>Besuche, Quellen, beliebte Seiten und Formular-Konversionen; Auswertung nach verfügbaren Messdaten und vereinbartem Datenschutzkonzept.</td></tr>
        </tbody></table></div>
        <Block title="Formulare mit tatsächlicher Verarbeitung"><p>Mehrsprachige Projekt- und Serviceformulare, Validierung, sichere Speicherung in der Datenbank sowie geschützte Dateiablage. Eingangsbestätigung für den Absender und E-Mail-Benachrichtigung an zuständige Mitarbeiter. Antworten erfolgen über das bestehende E-Mail-Programm; eine integrierte Mailbox ist nicht Bestandteil dieses Umfangs.</p></Block>
        <aside className="offer-note">Die Daten und Funktionen der bisherigen Admin-Demo sind Konzeptbeispiele. Die erste Phase umfasst keine Lagerverwaltung, Beschaffung, Wareneingänge, Lieferantenbewertung, Produktionsplanung oder ERP-Funktionen.</aside>
      </Sheet>
      <Sheet number={4} title="SEO & AEO">
        <p className="offer-intro">Die Website wird so strukturiert, dass potenzielle Kunden, Suchmaschinen und KI-basierte Antwortsysteme die Leistungen, Fachkompetenz und Referenzen von Kablitz verstehen können.</p>
        <Block title="Fachliche Tiefe statt einer festen Seitenzahl"><p>Themenplanung nach Leistungen, Kundenfragen und technischen Anwendungsfällen. Eigenständige Themen erhalten hilfreiche Fachseiten; zusammengehörige Fragen werden sinnvoll gebündelt. Dazu gehören technische Erläuterungen, Brennstoff- und Lösungsseiten, Serviceinformationen und nachvollziehbare Projektberichte.</p></Block>
        <Block title="Warum Kablitz? Mit konkreten Belegen."><p>Öffentliche Informationsseiten erklären die Stärken und Unterschiede von Kablitz: eigene Fertigung und Gießerei, Engineering, technische Erfahrung, Referenzen und Betreuung über den Anlagenlebenszyklus. Aussagen werden anhand freigegebener Unternehmensinformationen belegt.</p><p>Diese Seiten richten sich an Menschen und sind zugleich für Suchmaschinen und geeignete KI-Crawler technisch zugänglich. Sie enthalten klare Antworten, nachvollziehbare Fakten und passende interne Verknüpfungen.</p></Block>
        <Block title="Technische Optimierung"><ul><li>Strukturierte Seitenhierarchie, verständliche URLs und interne Verlinkung.</li><li>Individuelle Seitentitel und Beschreibungen, Canonicals und XML-Sitemap.</li><li>Sprachzuordnung mit hreflang und mehrsprachiger Navigation.</li><li>Inhaltlich passende strukturierte Daten und indexierbare Hauptinhalte.</li><li>Optimierung von Ladezeiten, Medien und Core Web Vitals.</li><li>Prüfung bestehender URLs und Einrichtung erforderlicher Weiterleitungen.</li><li>Einrichtung von Google Search Console und Bing Webmaster Tools in den Konten des Auftraggebers.</li></ul></Block>
        <aside className="offer-callout"><h3>Eine zusätzliche Fachseite pro Betreuungsmonat.</h3><p>ADSPIRE erstellt und veröffentlicht monatlich eine neue SEO-/AEO-optimierte Seite, einschließlich der deutschen, englischen, spanischen, französischen und italienischen Version. Themen und Fachinformationen werden mit Kablitz abgestimmt. Diese Leistung gilt auch während der drei kostenlosen Betreuungsmonate.</p></aside>
        <Block title="Klare redaktionelle Zuständigkeit"><p>Kablitz kann News und Projektseiten selbst im Admin veröffentlichen. Die zusätzlich betreuten SEO-/AEO-Fachseiten werden von ADSPIRE konzipiert, erstellt und technisch umgesetzt.</p></Block>
        <p className="offer-fine">Bessere Auffindbarkeit ist das Projektziel. Bestimmte Rankings, Traffic-Zahlen oder Nennungen in KI-Antworten können nicht garantiert werden.</p>
      </Sheet>
      <Sheet number={5} title="Umsetzung & Übergabe">
        <p className="offer-intro">Die Umsetzung beginnt unmittelbar nach Eingang der Anzahlung. Datenmodell, Design und technische Grundlagen werden vorbereitet, während die bereitgestellten Materialien laufend eingearbeitet werden.</p>
        <div className="offer-timeline"><div><span>Start</span><h3>Direkt nach Anzahlung</h3><p>Technische Basis, Datenbank, Gestaltung, Inhaltsstruktur und Abstimmung der Zugriffsrechte.</p></div><div><span>Ca. Woche 3</span><h3>Erste Veröffentlichung möglich</h3><p>Fertige, geprüfte und freigegebene Bereiche wie Startseite, Unternehmen und Kontakt können bereits online gehen.</p></div><div><span>Max. 2 Monate</span><h3>Vollständiger Projektumfang</h3><p>Weitere Fachseiten, Sprachversionen und Admin-Module werden ergänzt, getestet und übergeben.</p></div></div>
        <Block title="Schrittweise live gehen"><p>Die erste Veröffentlichung muss nicht bis zum Abschluss aller Module warten. Noch nicht fertige Bereiche werden nicht als funktionsfähig dargestellt. Bestehende wichtige Inhalte bleiben erreichbar oder werden sinnvoll weitergeleitet. Der konkrete Umfang jedes Veröffentlichungsschritts wird abgestimmt.</p></Block>
        <Block title="Überarbeitungen bis zur finalen Freigabe"><p>Design und vereinbarte Funktionen werden iterativ angepasst, bis Kablitz den abgestimmten Umfang freigibt. Enthalten sind Überarbeitungen innerhalb dieses Umfangs. Neue Module oder nachträgliche Erweiterungen werden separat vereinbart.</p></Block>
        <Block title="Materialien, Zugang & bestehende Website"><p>Kablitz stellt Fotos, Fachinformationen, Rückmeldungen und erforderliche Zugänge laufend bereit. Benötigt werden insbesondere Zugriff auf Domain/DNS und bei Bedarf das bestehende Hosting zur Übernahme relevanter Inhalte und Sicherung des bisherigen Auftritts. Vorhandene E-Mail-Dienste werden beim Domainwechsel berücksichtigt.</p><p>Eine Migration einer bisherigen Anwendung oder Datenbank ist nicht vorgesehen. Inhaltsübernahme und die Zuordnung wichtiger bestehender URLs sind Bestandteil des Relaunchs.</p></Block>
        <Block title="Vollständiges Eigentum am Projektcode"><p>Kablitz erhält den vollständigen entwickelten Quellcode, das Repository und die projektspezifischen Inhalte. Hosting, Datenbank und weitere Projektkonten werden dem Auftraggeber zugeordnet. Eine Einführung in CMS, Projektpflege und Anfragebearbeitung gehört zur Übergabe. Für eingesetzte Drittanbieter und Open-Source-Bibliotheken gelten deren eigene Lizenzen.</p></Block>
        <aside className="offer-note">Ziel: Abschluss spätestens zwei Monate nach Eingang der Anzahlung. Verzögerungen durch ausstehende Materialien, Zugänge oder Freigaben werden frühzeitig kommuniziert und gemeinsam im Zeitplan berücksichtigt.</aside>
      </Sheet>
      <Sheet number={6} title="Betreuung & nächste Phase">
        <Block title="Drei Monate Betreuung inklusive"><p>Ab der ersten öffentlichen Veröffentlichung der neuen Website auf der Kundendomain sind drei Monate des vereinbarten Betreuungspakets kostenlos enthalten. Bei einer schrittweisen Veröffentlichung beginnt dieser Zeitraum mit dem ersten Livegang. Danach kann die Betreuung monatlich fortgeführt werden.</p></Block>
        <Block title="Regelmäßige technische Betreuung"><p>Kontrolle von Hosting, Datenbank und bestehenden Seiten und Funktionen; Fehlerbehebung und erforderliche technische Wartung. Jeden Arbeitstag um 08:00 Uhr (Zeitzone Europe/Berlin) wird eine Prüfung der verfügbaren System- und Browserfehlerprotokolle vorgenommen. Hinzu kommt eine neue SEO-/AEO-Fachseite pro Monat in allen fünf Sprachen.</p><p>Die Bearbeitung erkannter oder gemeldeter Fehler beginnt am gleichen Arbeitstag. Probleme im eigenen Verantwortungsbereich werden nach Möglichkeit am selben Tag behoben. Bei externen Abhängigkeiten oder umfangreicheren Ursachen werden Maßnahmen und voraussichtliche Lösungszeiten mitgeteilt.</p></Block>
        <aside className="offer-callout"><h3>Sofortige Intervention bei kritischen Vorfällen.</h3><p>Bei Bekanntwerden eines kritischen Vorfalls – etwa eines Angriffs, eines Verdachts auf kompromittierte Zugänge oder eines vollständigen Website-Ausfalls – beginnt ADSPIRE unverzüglich mit Prüfung, Eindämmung und Wiederherstellung, auch an Wochenenden und Feiertagen. Die vollständige Behebung kann von Ursache und externen Anbietern abhängen.</p></aside>
        <Block title="Betrieb & Kündigung"><p>Vercel ist für das Hosting und Neon für die Datenbank vorgesehen. Infrastruktur, Dateiablage, E-Mail-Versand und weitere externe Dienste werden vom Auftraggeber nach den tatsächlichen Tarifen und der Nutzung getragen. Die Betreuung kann mit einer Frist von 30 Tagen gekündigt werden. Quellcode und Projektkonten verbleiben bei Kablitz.</p></Block>
        <Block title="Zahlungsrahmen"><p>20 % Anzahlung zum Projektstart. Der Restbetrag kann nach Vereinbarung auf bis zu acht monatliche Raten verteilt werden. Die monatliche Rate ist spätestens bis zum 15. des jeweiligen Monats zu zahlen, damit die laufenden Gehalts- und Steuerzahlungen planbar bleiben. Der konkrete Zahlungsplan wird vor Beauftragung festgelegt.</p><p className="offer-fine">Noch abzustimmender Vorschlag: Die erste Rate des Restbetrags wird einen Monat nach dem ersten öffentlichen Livegang fällig; weitere Raten folgen monatlich.</p></Block>
        <Block title="Phase 2: Anbindung an das bestehende ERP-/Lagersystem"><p>Die Synchronisation mit der vorhandenen Desktop- bzw. Lageranwendung ist ein separates Folgeprojekt. WinLine von mesonic ist ein möglicher, noch zu bestätigender Kandidat. Vor einer verbindlichen Planung werden Produkt, Version, Lizenzen, Schnittstellen, Datenumfang und Synchronisationsrichtung mit Kablitz und dem betreuenden Systempartner geprüft.</p></Block>
        <div className="offer-contact"><strong>ADSPIRE</strong><span>Inhaber: Đorđe Mladenović</span><span>Dimitrija Leka 66 · 18000 Niš (Palilula) · Serbien</span><span>PIB 114723739 · MB 67804961</span></div>
      </Sheet>
    </div>
  </main>;
}
